name: sandstone_example
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  scrollable_positioned_list: ^0.2.0-nullsafety.0
  provider: ^5.0.0
  tuple: ^2.0.0
  quiver: ^3.0.0
  flutter_keyboard_visibility: ^5.0.0
  cupertino_icons: ^1.0.2
  sandstone:


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  sandstone:
    path: ../

flutter:
  uses-material-design: true


