name: sandstone
description: An FSM backed state management solution
version: 1.0.0
author: Sam Marrs
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: