name: sandstone
description: An FSM backed state management solution
version: 1.0.0
author: Sam Marrs

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.0.15

dev_dependencies:
  build_runner: ^2.1.2
  build_test: ^2.1.3
  flutter_test:
    sdk: flutter
  test: ^1.16.8

flutter: