name: flutter_fsm
description: A new state management solution
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: