enum FSMEventIDs {
	// Transition queueing and Processing events
	TRANSITION_IGNORED,
	TRANSITION_PROCESS_STARTED,
	STATE_TRANSITION_STARTED,
	MIRRORED_STATE_TRANSITION_STARTED,
	FF_MIRRORED_TRANSITION_STARTED,
	VALID_STATE_NOT_FOUND,
	STATE_CHANGED,
	BUFFER_PURGED,
	RUNNING_TRANSITION_ACTIONS,
	PROPAGATING_STATE_CHANGES,
	RUNNING_STATE_ACTIONS,
	TRANSITION_PROCESS_ENDED,
	// General runtime events
	UNKNOWN_STATE_TUPLE,
	UNKNOWN_STATE_VALUE,
	// FSM Mirroring error events
	FSM_MIRROR_NO_REUSED_STATE_VALUE,
	FSM_MIRROR_NO_REUSED_TRANSITION,
	FSM_MIRROR_NO_UNCHANGED_STATE_VALUE
}