enum FSMEventIDs {
	TRANSITION_IGNORED,
	TRANSITION_PROCESS_STARTED,
	STATE_TRANSITION_STARTED,
	MIRRORED_STATE_TRANSITION_STARTED,
	FF_MIRRORED_TRANSITION_STARTED,
	VALID_STATE_NOT_FOUND,
	STATE_CHANGED,
	BUFFER_PURGED,
	RUNNING_TRANSITION_ACTIONS,
	PROPAGATING_STATE_CHANGES,
	RUNNING_STATE_ACTIONS,
	TRANSITION_PROCESS_ENDED,
}